name: Retry
on:  
   workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'location'
        required: false
        default: 'The Octoverse'
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - uses: zwaldowski/git-commit-action@v1
        with:
          commit_message: "Commit test"
